"""Add total fields to lpo table

Revision ID: 0035cdbb7765
Revises: aef65da12420
Create Date: 2025-09-23 09:24:30.179424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0035cdbb7765'
down_revision: Union[str, Sequence[str], None] = 'aef65da12420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lpos', sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('lpos', sa.Column('tax_total', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('lpos', sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lpos', 'grand_total')
    op.drop_column('lpos', 'tax_total')
    op.drop_column('lpos', 'subtotal')
    # ### end Alembic commands ###
