"""Add ToolboxVideo model

Revision ID: 004e2bd09eac
Revises: d9ebc8f0f3e3
Create Date: 2025-09-08 09:35:58.567159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004e2bd09eac'
down_revision: Union[str, Sequence[str], None] = 'd9ebc8f0f3e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toolbox_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_card_id', sa.Integer(), nullable=True),
    sa.Column('duty_officer_progress_id', sa.Integer(), nullable=True),
    sa.Column('blob_url', sa.String(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['duty_officer_progress_id'], ['duty_officer_progress.id'], ),
    sa.ForeignKeyConstraint(['job_card_id'], ['job_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toolbox_videos_id'), 'toolbox_videos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_toolbox_videos_id'), table_name='toolbox_videos')
    op.drop_table('toolbox_videos')
    # ### end Alembic commands ###
