"""Add MaterialRequisition model

Revision ID: 03b45eab6e2f
Revises: b22543106a5d
Create Date: 2025-09-06 14:46:02.714032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b45eab6e2f'
down_revision: Union[str, Sequence[str], None] = 'b22543106a5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_requisitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.String(), nullable=False),
    sa.Column('material_with_quantity', sa.Text(), nullable=False),
    sa.Column('urgency', sa.String(), nullable=False),
    sa.Column('required_delivery_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['supervisors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_requisitions_id'), 'material_requisitions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_requisitions_id'), table_name='material_requisitions')
    op.drop_table('material_requisitions')
    # ### end Alembic commands ###
