"""Add material requisition comments table

Revision ID: 05b1797d6982
Revises: 26ec98c3e539
Create Date: 2025-09-18 14:40:16.091268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05b1797d6982'
down_revision: Union[str, Sequence[str], None] = '26ec98c3e539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mr_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('comment_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requisition_id'], ['material_requisitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mr_comments_id'), 'mr_comments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mr_comments_id'), table_name='mr_comments')
    op.drop_table('mr_comments')
    # ### end Alembic commands ###
