"""Add signoff fields to design tasks

Revision ID: 085400c69d0f
Revises: 90930520709a
Create Date: 2025-09-27 10:19:13.150301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '085400c69d0f'
down_revision: Union[str, Sequence[str], None] = '90930520709a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_tasks', sa.Column('signed_off_at', sa.DateTime(), nullable=True))
    op.add_column('design_tasks', sa.Column('sign_off_notes', sa.Text(), nullable=True))
    op.add_column('design_tasks', sa.Column('signed_off_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'design_tasks', 'users', ['signed_off_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'design_tasks', type_='foreignkey')
    op.drop_column('design_tasks', 'signed_off_by_id')
    op.drop_column('design_tasks', 'sign_off_notes')
    op.drop_column('design_tasks', 'signed_off_at')
    # ### end Alembic commands ###
