"""Create v3 interdisciplinary signoffs table

Revision ID: 098f217de945
Revises: e82efea2f69b
Create Date: 2025-10-10 12:47:35.036392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098f217de945'
down_revision: Union[str, Sequence[str], None] = 'e82efea2f69b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interdisciplinary_signoffs_v3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discipline', sa.String(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('signed_off_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('signed_off_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['signed_off_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['design_stages_v3.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interdisciplinary_signoffs_v3')
    # ### end Alembic commands ###
