"""Add design tasks v3 table and relationships

Revision ID: 0efa80422b5f
Revises: 76b15f63dd62
Create Date: 2025-10-08 15:06:34.499834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0efa80422b5f'
down_revision: Union[str, Sequence[str], None] = '76b15f63dd62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
