"""Add created_by_id to progress and site reports

Revision ID: 11d1e4385889
Revises: 87cf49c95be9
Create Date: 2025-09-13 09:41:29.224967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11d1e4385889'
down_revision: Union[str, Sequence[str], None] = '87cf49c95be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duty_officer_progress', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'duty_officer_progress', 'users', ['created_by_id'], ['id'])
    op.add_column('site_officer_reports', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'site_officer_reports', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site_officer_reports', type_='foreignkey')
    op.drop_column('site_officer_reports', 'created_by_id')
    op.drop_constraint(None, 'duty_officer_progress', type_='foreignkey')
    op.drop_column('duty_officer_progress', 'created_by_id')
    # ### end Alembic commands ###
