"""Add SiteOfficerReport model for Form C

Revision ID: 19e42b303eaa
Revises: 7d1ebef5e597
Create Date: 2025-09-06 13:06:55.372740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e42b303eaa'
down_revision: Union[str, Sequence[str], None] = '7d1ebef5e597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_officer_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('site_location', sa.String(), nullable=False),
    sa.Column('site_officer_id', sa.Integer(), nullable=False),
    sa.Column('duty_officer_id', sa.Integer(), nullable=False),
    sa.Column('tbt_attendance', sa.Text(), nullable=True),
    sa.Column('tbt_topic_discussed', sa.String(), nullable=True),
    sa.Column('tbt_key_points', sa.Text(), nullable=True),
    sa.Column('job_card_id', sa.Integer(), nullable=False),
    sa.Column('form_b_completed_check', sa.Boolean(), nullable=True),
    sa.Column('dependency_notes', sa.Text(), nullable=True),
    sa.Column('progress_pictures_check', sa.Boolean(), nullable=True),
    sa.Column('sm_manpower_availability', sa.Text(), nullable=True),
    sa.Column('sm_subcontractor_coordination', sa.String(), nullable=True),
    sa.Column('sm_coordination_issues', sa.Text(), nullable=True),
    sa.Column('sm_other_notes', sa.Text(), nullable=True),
    sa.Column('material_requisition_project_id', sa.Integer(), nullable=True),
    sa.Column('commercial_delivery_check', sa.Boolean(), nullable=True),
    sa.Column('delivery_comments', sa.Text(), nullable=True),
    sa.Column('qc_steps_explained', sa.Boolean(), nullable=True),
    sa.Column('qc_steps_details', sa.Text(), nullable=True),
    sa.Column('qc_drawing_mismatches', sa.Text(), nullable=True),
    sa.Column('re_delays_flagged_reason', sa.Text(), nullable=True),
    sa.Column('re_support_needed', sa.Text(), nullable=True),
    sa.Column('hs_waste_management', sa.String(), nullable=True),
    sa.Column('hs_waste_management_comments', sa.Text(), nullable=True),
    sa.Column('hs_walkways_clear', sa.String(), nullable=True),
    sa.Column('hs_material_storage', sa.String(), nullable=True),
    sa.Column('hs_ppe_compliance', sa.Boolean(), nullable=True),
    sa.Column('hs_incidents_near_misses', sa.Text(), nullable=True),
    sa.Column('hs_safety_comments', sa.Text(), nullable=True),
    sa.Column('sa_overall_site_health', sa.String(), nullable=True),
    sa.Column('sa_immediate_actions', sa.Text(), nullable=True),
    sa.Column('sa_responsible_person', sa.String(), nullable=True),
    sa.Column('sa_action_deadline', sa.Date(), nullable=True),
    sa.Column('sa_critical_actions', sa.Text(), nullable=True),
    sa.Column('sa_approved_drawings_check', sa.String(), nullable=True),
    sa.Column('sa_drawing_help_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['duty_officer_id'], ['foremen.id'], ),
    sa.ForeignKeyConstraint(['job_card_id'], ['job_cards.id'], ),
    sa.ForeignKeyConstraint(['material_requisition_project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['site_officer_id'], ['supervisors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_officer_reports_id'), 'site_officer_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_officer_reports_id'), table_name='site_officer_reports')
    op.drop_table('site_officer_reports')
    # ### end Alembic commands ###
