"""Add design workflow v2 tables

Revision ID: 2122175e6966
Revises: 9f7437852b08
Create Date: 2025-10-06 15:12:47.446831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2122175e6966'
down_revision: Union[str, Sequence[str], None] = '9f7437852b08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('design_projects_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('client', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('finance_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('STAGE_2A', 'STAGE_3', 'STAGE_4', 'STAGE_5', 'STAGE_6', 'STAGE_7', 'STAGE_8', name='stagename'), nullable=False),
    sa.Column('status', sa.Enum('LOCKED', 'IN_PROGRESS', 'COMPLETED', name='stagestatus'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['design_projects_v2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design_tasks_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'SUBMITTED', 'REVISION', 'APPROVED', 'VERIFIED', name='taskstatusv2'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('file_link', sa.Text(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['design_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interdisciplinary_signoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discipline', sa.String(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('signed_off_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('signed_off_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['signed_off_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['design_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_visit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('meeting_held_at', sa.DateTime(), nullable=True),
    sa.Column('mom_link', sa.Text(), nullable=True),
    sa.Column('site_photos_link', sa.Text(), nullable=True),
    sa.Column('updated_brief_link', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['design_stages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_visit_logs')
    op.drop_table('interdisciplinary_signoffs')
    op.drop_table('design_tasks_v2')
    op.drop_table('design_stages')
    op.drop_table('design_projects_v2')
    # ### end Alembic commands ###
