"""Add nanny log table

Revision ID: 26ec98c3e539
Revises: 9e583a788e95
Create Date: 2025-09-18 11:18:55.962438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ec98c3e539'
down_revision: Union[str, Sequence[str], None] = '9e583a788e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nanny_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nanny_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('handwashing_checks', sa.String(), nullable=True),
    sa.Column('environment_checks', sa.String(), nullable=True),
    sa.Column('breakfast_details', sa.Text(), nullable=True),
    sa.Column('breakfast_amount', sa.String(), nullable=True),
    sa.Column('lunch_details', sa.Text(), nullable=True),
    sa.Column('lunch_amount', sa.String(), nullable=True),
    sa.Column('snack_details', sa.Text(), nullable=True),
    sa.Column('snack_amount', sa.String(), nullable=True),
    sa.Column('dinner_details', sa.Text(), nullable=True),
    sa.Column('dinner_amount', sa.String(), nullable=True),
    sa.Column('hydration_morning_cups', sa.String(), nullable=True),
    sa.Column('hydration_afternoon_cups', sa.String(), nullable=True),
    sa.Column('hydration_evening_cups', sa.String(), nullable=True),
    sa.Column('restricted_foods_given', sa.Boolean(), nullable=True),
    sa.Column('restricted_foods_details', sa.Text(), nullable=True),
    sa.Column('nap_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('bedtime_by_830pm', sa.Boolean(), nullable=True),
    sa.Column('total_sleep_hours', sa.String(), nullable=True),
    sa.Column('outdoor_play_completed', sa.Boolean(), nullable=True),
    sa.Column('outdoor_play_minutes', sa.Integer(), nullable=True),
    sa.Column('screen_time_minutes', sa.Integer(), nullable=True),
    sa.Column('temperature_celsius', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('appetite', sa.String(), nullable=True),
    sa.Column('behavior', sa.String(), nullable=True),
    sa.Column('signs_of_illness', sa.Text(), nullable=True),
    sa.Column('nanny_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['nanny_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nanny_logs_id'), 'nanny_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nanny_logs_id'), table_name='nanny_logs')
    op.drop_table('nanny_logs')
    # ### end Alembic commands ###
