"""Add deal_id to design project v2

Revision ID: 27f236432d28
Revises: a013030b4d97
Create Date: 2025-10-08 09:39:22.451620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f236432d28'
down_revision: Union[str, Sequence[str], None] = 'a013030b4d97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_projects_v2', sa.Column('deal_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'design_projects_v2', ['deal_id'])
    op.create_foreign_key(None, 'design_projects_v2', 'deals', ['deal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'design_projects_v2', type_='foreignkey')
    op.drop_constraint(None, 'design_projects_v2', type_='unique')
    op.drop_column('design_projects_v2', 'deal_id')
    # ### end Alembic commands ###
