"""Add created_by to material requisition

Revision ID: 301e58c14354
Revises: bce36e94c676
Create Date: 2025-09-30 13:56:54.996807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '301e58c14354'
down_revision: Union[str, Sequence[str], None] = 'bce36e94c676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_requisitions', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'material_requisitions', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'material_requisitions', type_='foreignkey')
    op.drop_column('material_requisitions', 'created_by_id')
    # ### end Alembic commands ###
