"""Add tech spec and boq mapping to MR

Revision ID: 31e97e3496e4
Revises: 7bb4c4622eab
Create Date: 2025-09-30 09:31:49.690388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e97e3496e4'
down_revision: Union[str, Sequence[str], None] = '7bb4c4622eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_requisitions', sa.Column('technical_spec', sa.Text(), nullable=True))
    op.add_column('material_requisitions', sa.Column('boq_mapping', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_requisitions', 'boq_mapping')
    op.drop_column('material_requisitions', 'technical_spec')
    # ### end Alembic commands ###
