"""Change role name from enum to string

Revision ID: 3d5374ee16ac
Revises: f4387ac45d8b
Create Date: 2025-09-22 15:21:32.136501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d5374ee16ac'
down_revision: Union[str, Sequence[str], None] = 'f4387ac45d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=postgresql.ENUM('SUPER_ADMIN', 'ADMIN', 'OPERATION_MANAGER', 'PROJECT_MANAGER', 'SITE_ENGINEER', 'SUPERVISOR', 'FOREMAN', 'PROCUREMENT', 'USER', 'QS', 'Finance', name='userrole'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=sa.String(),
               type_=postgresql.ENUM('SUPER_ADMIN', 'ADMIN', 'OPERATION_MANAGER', 'PROJECT_MANAGER', 'SITE_ENGINEER', 'SUPERVISOR', 'FOREMAN', 'PROCUREMENT', 'USER', 'QS', 'Finance', name='userrole'),
               existing_nullable=False)
    # ### end Alembic commands ###
