"""Make Form C fields optional and job cards many-to-many

Revision ID: 40cc876b2675
Revises: b148321ad195
Create Date: 2025-09-30 11:22:01.918563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40cc876b2675'
down_revision: Union[str, Sequence[str], None] = 'b148321ad195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_jc_association',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('job_card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_card_id'], ['job_cards.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['site_officer_reports.id'], ),
    sa.PrimaryKeyConstraint('report_id', 'job_card_id')
    )
    op.alter_column('site_officer_reports', 'site_location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('site_officer_reports', 'site_officer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site_officer_reports', 'duty_officer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('site_officer_reports_job_card_id_fkey'), 'site_officer_reports', type_='foreignkey')
    op.drop_column('site_officer_reports', 'job_card_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_officer_reports', sa.Column('job_card_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('site_officer_reports_job_card_id_fkey'), 'site_officer_reports', 'job_cards', ['job_card_id'], ['id'])
    op.alter_column('site_officer_reports', 'duty_officer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site_officer_reports', 'site_officer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site_officer_reports', 'site_location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('report_jc_association')
    # ### end Alembic commands ###
