"""Add SiteImage model for multi-image uploads

Revision ID: 42b2b3a01914
Revises: f66be99a0a37
Create Date: 2025-09-08 10:57:33.987879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b2b3a01914'
down_revision: Union[str, Sequence[str], None] = 'f66be99a0a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duty_officer_progress_id', sa.Integer(), nullable=True),
    sa.Column('site_officer_report_id', sa.Integer(), nullable=True),
    sa.Column('blob_url', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['duty_officer_progress_id'], ['duty_officer_progress.id'], ),
    sa.ForeignKeyConstraint(['site_officer_report_id'], ['site_officer_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_images_id'), 'site_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_images_id'), table_name='site_images')
    op.drop_table('site_images')
    # ### end Alembic commands ###
