"""Add status to JobCard and Task models

Revision ID: 4a1d4b403dcf
Revises: 42b2b3a01914
Create Date: 2025-09-08 11:56:44.248772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a1d4b403dcf'
down_revision: Union[str, Sequence[str], None] = '42b2b3a01914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('job_cards', sa.Column('status', sa.String(), nullable=False))
    # op.create_index(op.f('ix_job_cards_status'), 'job_cards', ['status'], unique=False)
    op.add_column('job_cards', sa.Column('status', sa.String(), nullable=False, server_default='Pending'))
    op.create_index(op.f('ix_job_cards_status'), 'job_cards', ['status'], unique=False)
    #op.add_column('tasks', sa.Column('status', sa.String(), nullable=False))
    #op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.add_column('tasks', sa.Column('status', sa.String(), nullable=False, server_default='Pending'))
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_column('tasks', 'status')
    op.drop_index(op.f('ix_job_cards_status'), table_name='job_cards')
    op.drop_column('job_cards', 'status')
    # ### end Alembic commands ###
