"""Add foreman_user_id to duty officer progress

Revision ID: 5fc6aad8ae5f
Revises: 11d1e4385889
Create Date: 2025-09-13 09:49:38.884130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc6aad8ae5f'
down_revision: Union[str, Sequence[str], None] = '11d1e4385889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duty_officer_progress', sa.Column('foreman_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'duty_officer_progress', 'users', ['foreman_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'duty_officer_progress', type_='foreignkey')
    op.drop_column('duty_officer_progress', 'foreman_user_id')
    # ### end Alembic commands ###
