"""Add payment mode to lpo

Revision ID: 6898f0262850
Revises: 31e97e3496e4
Create Date: 2025-09-30 10:18:21.226653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6898f0262850'
down_revision: Union[str, Sequence[str], None] = '31e97e3496e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lpos', sa.Column('payment_mode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lpos', 'payment_mode')
    # ### end Alembic commands ###
