"""Add mr_approval to material requisition

Revision ID: 6aab78507ee6
Revises: 718a7ef55f5c
Create Date: 2025-09-18 15:38:16.432945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aab78507ee6'
down_revision: Union[str, Sequence[str], None] = '718a7ef55f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_requisitions', sa.Column('mr_approval', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_requisitions', 'mr_approval')
    # ### end Alembic commands ###
