"""Add user_id fks to site officer reports

Revision ID: 6f39bf21a2b1
Revises: 5fc6aad8ae5f
Create Date: 2025-09-13 09:58:18.369407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f39bf21a2b1'
down_revision: Union[str, Sequence[str], None] = '5fc6aad8ae5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_officer_reports', sa.Column('site_officer_user_id', sa.Integer(), nullable=True))
    op.add_column('site_officer_reports', sa.Column('duty_officer_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'site_officer_reports', 'users', ['site_officer_user_id'], ['id'])
    op.create_foreign_key(None, 'site_officer_reports', 'users', ['duty_officer_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site_officer_reports', type_='foreignkey')
    op.drop_constraint(None, 'site_officer_reports', type_='foreignkey')
    op.drop_column('site_officer_reports', 'duty_officer_user_id')
    op.drop_column('site_officer_reports', 'site_officer_user_id')
    # ### end Alembic commands ###
