"""Make mr_number non-nullable

Revision ID: 718a7ef55f5c
Revises: 05b1797d6982
Create Date: 2025-09-18 15:05:32.962954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '718a7ef55f5c'
down_revision: Union[str, Sequence[str], None] = '05b1797d6982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('material_requisitions', 'mr_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('material_requisitions', 'mr_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
