"""Add site visit log table for V3

Revision ID: 76b15f63dd62
Revises: 30e7bbdf7110
Create Date: 2025-10-08 14:33:45.367411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76b15f63dd62'
down_revision: Union[str, Sequence[str], None] = '30e7bbdf7110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_design_task_comments_id'), table_name='design_task_comments')
    op.drop_table('design_task_comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('design_task_comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('comment_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_by_id'], ['users.id'], name=op.f('design_task_comments_comment_by_id_fkey')),
    sa.ForeignKeyConstraint(['task_id'], ['design_tasks.id'], name=op.f('design_task_comments_task_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('design_task_comments_pkey'))
    )
    op.create_index(op.f('ix_design_task_comments_id'), 'design_task_comments', ['id'], unique=False)
    # ### end Alembic commands ###
