"""Add parsed user agent fields to auth log

Revision ID: 7bb4c4622eab
Revises: 8557eabd919b
Create Date: 2025-09-29 09:35:01.183573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bb4c4622eab'
down_revision: Union[str, Sequence[str], None] = '8557eabd919b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_logs', sa.Column('browser', sa.String(), nullable=True))
    op.add_column('auth_logs', sa.Column('os', sa.String(), nullable=True))
    op.add_column('auth_logs', sa.Column('device', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_logs', 'device')
    op.drop_column('auth_logs', 'os')
    op.drop_column('auth_logs', 'browser')
    # ### end Alembic commands ###
