"""Add DutyOfficerProgress model for Form B

Revision ID: 7d1ebef5e597
Revises: 8c0147ce258d
Create Date: 2025-09-06 11:54:27.833935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d1ebef5e597'
down_revision: Union[str, Sequence[str], None] = '8c0147ce258d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duty_officer_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_card_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('date_of_work', sa.Date(), nullable=False),
    sa.Column('actual_output', sa.Text(), nullable=False),
    sa.Column('issues_delays', sa.Text(), nullable=False),
    sa.Column('tbt_attendance', sa.Text(), nullable=False),
    sa.Column('tbt_topic_discussed', sa.String(), nullable=True),
    sa.Column('tbt_key_points', sa.Text(), nullable=False),
    sa.Column('sm_equipment_inventory', sa.Text(), nullable=False),
    sa.Column('sm_equipment_condition', sa.String(), nullable=True),
    sa.Column('sm_equipment_transfer', sa.String(), nullable=True),
    sa.Column('sm_remarks', sa.Text(), nullable=True),
    sa.Column('sm_sub_contractor_coordination', sa.String(), nullable=True),
    sa.Column('sm_coordination_issues', sa.Text(), nullable=True),
    sa.Column('sm_ppe_check', sa.Boolean(), nullable=True),
    sa.Column('sm_safety_hazards', sa.Text(), nullable=False),
    sa.Column('sm_photos_on_whatsapp', sa.Boolean(), nullable=True),
    sa.Column('sm_foreman_signature_id', sa.Integer(), nullable=False),
    sa.Column('mm_deliveries_received', sa.String(), nullable=False),
    sa.Column('mm_rejection_reason', sa.Text(), nullable=True),
    sa.Column('mm_stock_balance', sa.Text(), nullable=False),
    sa.Column('mm_material_transfers', sa.String(), nullable=True),
    sa.Column('kt_sops_explained', sa.String(), nullable=True),
    sa.Column('kt_help_required_details', sa.Text(), nullable=True),
    sa.Column('kt_critical_actions_required', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_card_id'], ['job_cards.id'], ),
    sa.ForeignKeyConstraint(['sm_foreman_signature_id'], ['foremen.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duty_officer_progress_id'), 'duty_officer_progress', ['id'], unique=False)
    op.drop_index(op.f('ix_foremen_id'), table_name='foremen')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_site_engineers_id'), table_name='site_engineers')
    op.drop_index(op.f('ix_supervisors_id'), table_name='supervisors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_supervisors_id'), 'supervisors', ['id'], unique=False)
    op.create_index(op.f('ix_site_engineers_id'), 'site_engineers', ['id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_foremen_id'), 'foremen', ['id'], unique=False)
    op.drop_index(op.f('ix_duty_officer_progress_id'), table_name='duty_officer_progress')
    op.drop_table('duty_officer_progress')
    # ### end Alembic commands ###
