"""Add auth log table

Revision ID: 8557eabd919b
Revises: 085400c69d0f
Create Date: 2025-09-29 09:01:18.200818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8557eabd919b'
down_revision: Union[str, Sequence[str], None] = '085400c69d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_logs_id'), 'auth_logs', ['id'], unique=False)
    #op.add_column('users', sa.Column('session_id', sa.UUID(), nullable=False))
    op.add_column(
        'users', 
        sa.Column(
            'session_id', 
            sa.UUID(), 
            nullable=False, 
            server_default=sa.text('gen_random_uuid()')  # <-- ADD THIS PART
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'session_id')
    op.drop_index(op.f('ix_auth_logs_id'), table_name='auth_logs')
    op.drop_table('auth_logs')
    # ### end Alembic commands ###
