"""Add user assignment and created_by columns

Revision ID: 87cf49c95be9
Revises: 830bbdef951c
Create Date: 2025-09-12 14:26:11.182003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87cf49c95be9'
down_revision: Union[str, Sequence[str], None] = '830bbdef951c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_cards', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('job_cards', sa.Column('site_engineer_user_id', sa.Integer(), nullable=True))
    op.add_column('job_cards', sa.Column('supervisor_user_id', sa.Integer(), nullable=True))
    op.add_column('job_cards', sa.Column('foreman_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job_cards', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'job_cards', 'users', ['foreman_user_id'], ['id'])
    op.create_foreign_key(None, 'job_cards', 'users', ['supervisor_user_id'], ['id'])
    op.create_foreign_key(None, 'job_cards', 'users', ['site_engineer_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_cards', type_='foreignkey')
    op.drop_constraint(None, 'job_cards', type_='foreignkey')
    op.drop_constraint(None, 'job_cards', type_='foreignkey')
    op.drop_constraint(None, 'job_cards', type_='foreignkey')
    op.drop_column('job_cards', 'foreman_user_id')
    op.drop_column('job_cards', 'supervisor_user_id')
    op.drop_column('job_cards', 'site_engineer_user_id')
    op.drop_column('job_cards', 'created_by_id')
    # ### end Alembic commands ###
