"""Add closed_at to design project

Revision ID: 88453e32ecd6
Revises: 301e58c14354
Create Date: 2025-10-02 09:40:17.458674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88453e32ecd6'
down_revision: Union[str, Sequence[str], None] = '301e58c14354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_projects', sa.Column('closed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('design_projects', 'closed_at')
    # ### end Alembic commands ###
