"""Add many-to-many link between mr and jc

Revision ID: 89a73c6d06c7
Revises: e4a840333f8a
Create Date: 2025-09-20 12:18:47.384835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89a73c6d06c7'
down_revision: Union[str, Sequence[str], None] = 'e4a840333f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mr_jc_association',
    sa.Column('material_requisition_id', sa.Integer(), nullable=False),
    sa.Column('job_card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_card_id'], ['job_cards.id'], ),
    sa.ForeignKeyConstraint(['material_requisition_id'], ['material_requisitions.id'], ),
    sa.PrimaryKeyConstraint('material_requisition_id', 'job_card_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mr_jc_association')
    # ### end Alembic commands ###
