"""Add design workflow module tables

Revision ID: 8f7dff70712c
Revises: 77af3a27aa53
Create Date: 2025-09-25 11:36:06.337045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f7dff70712c'
down_revision: Union[str, Sequence[str], None] = '77af3a27aa53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('design_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('client', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_projects_id'), 'design_projects', ['id'], unique=False)
    op.create_table('design_phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('PHASE_2', 'PHASE_4', 'PHASE_5', name='designphasename'), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['design_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_phases_id'), 'design_phases', ['id'], unique=False)
    op.create_table('design_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'SUBMITTED', 'REVISION_REQUESTED', 'VERIFIED', 'DONE', name='designtaskstatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('file_link', sa.Text(), nullable=True),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['phase_id'], ['design_phases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_tasks_id'), 'design_tasks', ['id'], unique=False)
    op.create_table('design_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('lateness_days', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['design_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index(op.f('ix_design_scores_id'), 'design_scores', ['id'], unique=False)
    op.create_table('design_task_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('comment_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['design_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_task_comments_id'), 'design_task_comments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_design_task_comments_id'), table_name='design_task_comments')
    op.drop_table('design_task_comments')
    op.drop_index(op.f('ix_design_scores_id'), table_name='design_scores')
    op.drop_table('design_scores')
    op.drop_index(op.f('ix_design_tasks_id'), table_name='design_tasks')
    op.drop_table('design_tasks')
    op.drop_index(op.f('ix_design_phases_id'), table_name='design_phases')
    op.drop_table('design_phases')
    op.drop_index(op.f('ix_design_projects_id'), table_name='design_projects')
    op.drop_table('design_projects')
    # ### end Alembic commands ###
