"""Add verification fields to design tasks

Revision ID: 90930520709a
Revises: 8f7dff70712c
Create Date: 2025-09-27 08:21:59.045689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90930520709a'
down_revision: Union[str, Sequence[str], None] = '8f7dff70712c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_tasks', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.add_column('design_tasks', sa.Column('verified_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'design_tasks', 'users', ['verified_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'design_tasks', type_='foreignkey')
    op.drop_column('design_tasks', 'verified_by_id')
    op.drop_column('design_tasks', 'verified_at')
    # ### end Alembic commands ###
