"""Add delivery_datetime to measurement_requisitions

Revision ID: 9bf8fff09dcc
Revises: 9e3c65958c67
Create Date: 2025-10-13 11:23:19.300963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bf8fff09dcc'
down_revision: Union[str, Sequence[str], None] = '9e3c65958c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement_requisitions', sa.Column('delivery_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurement_requisitions', 'delivery_datetime')
    # ### end Alembic commands ###
