"""Create site_visit_logs_v3 table

Revision ID: 9e3c65958c67
Revises: bf201ab821a4
Create Date: 2025-10-13 11:03:15.630502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e3c65958c67'
down_revision: Union[str, Sequence[str], None] = 'bf201ab821a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_visit_logs_v3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_held_at', sa.DateTime(), nullable=True),
    sa.Column('mom_link', sa.Text(), nullable=True),
    sa.Column('site_photos_link', sa.Text(), nullable=True),
    sa.Column('updated_brief_link', sa.Text(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['design_stages_v3.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_visit_logs_v3')
    # ### end Alembic commands ###
