"""Add user_id fks to material requisit table

Revision ID: 9e583a788e95
Revises: 6f39bf21a2b1
Create Date: 2025-09-13 10:05:29.363085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e583a788e95'
down_revision: Union[str, Sequence[str], None] = '6f39bf21a2b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('material_requisitions_requested_by_id_fkey'), 'material_requisitions', type_='foreignkey')
    op.create_foreign_key(None, 'material_requisitions', 'users', ['requested_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'material_requisitions', type_='foreignkey')
    op.create_foreign_key(op.f('material_requisitions_requested_by_id_fkey'), 'material_requisitions', 'supervisors', ['requested_by_id'], ['id'])
    # ### end Alembic commands ###
