"""Add initial design v3 models

Revision ID: a013030b4d97
Revises: a0754ca56759
Create Date: 2025-10-07 15:01:55.382645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a013030b4d97'
down_revision: Union[str, Sequence[str], None] = 'a0754ca56759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_contact', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('contract_type', sa.Enum('DESIGN_BUILD', 'GUESSTIMATE', 'DESIGN_ONLY', 'GOLD_VR', name='commitmentpackage'), nullable=False),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('initial_brief_link', sa.Text(), nullable=True),
    sa.Column('floor_plan_link', sa.Text(), nullable=True),
    sa.Column('as_built_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sip_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sip_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deals')
    # ### end Alembic commands ###
