"""Add many-to-many link between lpo and mr

Revision ID: a63206b036a1
Revises: 88453e32ecd6
Create Date: 2025-10-03 15:11:59.988223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63206b036a1'
down_revision: Union[str, Sequence[str], None] = '88453e32ecd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lpo_mr_association',
    sa.Column('lpo_id', sa.Integer(), nullable=False),
    sa.Column('material_requisition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lpo_id'], ['lpos.id'], ),
    sa.ForeignKeyConstraint(['material_requisition_id'], ['material_requisitions.id'], ),
    sa.PrimaryKeyConstraint('lpo_id', 'material_requisition_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lpo_mr_association')
    # ### end Alembic commands ###
