"""Add full design v3 models

Revision ID: a8116ad7e803
Revises: 27f236432d28
Create Date: 2025-10-08 10:00:44.230580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8116ad7e803'
down_revision: Union[str, Sequence[str], None] = '27f236432d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('design_projects_v3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('client', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id')
    )
    op.create_table('design_stages_v3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('FINANCE_CONFIRMATION', 'DEAL_CREATION', 'SITE_VISIT', 'MEASUREMENT', 'INITIAL_DESIGN', 'QS_HANDOVER', 'MANAGEMENT_OVERSIGHT', 'TECH_REVIEW', 'AUTHORITY_PACKAGE', 'FINAL_DELIVERY', 'EXECUTION_HANDOVER', name='stagename'), nullable=False),
    sa.Column('status', sa.Enum('LOCKED', 'IN_PROGRESS', 'COMPLETED', name='stagev3status'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['design_projects_v3.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('design_stages_v3')
    op.drop_table('design_projects_v3')
    # ### end Alembic commands ###
