"""Add handover fields to design project v3

Revision ID: acbffcf293e0
Revises: 098f217de945
Create Date: 2025-10-10 14:55:48.177597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acbffcf293e0'
down_revision: Union[str, Sequence[str], None] = '098f217de945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_projects_v3', sa.Column('handover_design_head_signed_by_id', sa.Integer(), nullable=True))
    op.add_column('design_projects_v3', sa.Column('handover_design_head_signed_at', sa.DateTime(), nullable=True))
    op.add_column('design_projects_v3', sa.Column('handover_ops_head_signed_by_id', sa.Integer(), nullable=True))
    op.add_column('design_projects_v3', sa.Column('handover_ops_head_signed_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'design_projects_v3', 'users', ['handover_ops_head_signed_by_id'], ['id'])
    op.create_foreign_key(None, 'design_projects_v3', 'users', ['handover_design_head_signed_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'design_projects_v3', type_='foreignkey')
    op.drop_constraint(None, 'design_projects_v3', type_='foreignkey')
    op.drop_column('design_projects_v3', 'handover_ops_head_signed_at')
    op.drop_column('design_projects_v3', 'handover_ops_head_signed_by_id')
    op.drop_column('design_projects_v3', 'handover_design_head_signed_at')
    op.drop_column('design_projects_v3', 'handover_design_head_signed_by_id')
    # ### end Alembic commands ###
