"""Add LPO module tables

Revision ID: aef65da12420
Revises: 3d5374ee16ac
Create Date: 2025-09-22 15:25:16.961215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef65da12420'
down_revision: Union[str, Sequence[str], None] = '3d5374ee16ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lpos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lpo_number', sa.String(), nullable=False),
    sa.Column('lpo_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message_to_supplier', sa.Text(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lpo_number')
    )
    op.create_index(op.f('ix_lpos_id'), 'lpos', ['id'], unique=False)
    op.create_table('lpo_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blob_url', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('lpo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lpo_id'], ['lpos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lpo_attachments_id'), 'lpo_attachments', ['id'], unique=False)
    op.create_table('lpo_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('lpo_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lpo_id'], ['lpos.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lpo_items_id'), 'lpo_items', ['id'], unique=False)
    op.create_table('lpo_item_project_association',
    sa.Column('lpo_item_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lpo_item_id'], ['lpo_items.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('lpo_item_id', 'project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lpo_item_project_association')
    op.drop_index(op.f('ix_lpo_items_id'), table_name='lpo_items')
    op.drop_table('lpo_items')
    op.drop_index(op.f('ix_lpo_attachments_id'), table_name='lpo_attachments')
    op.drop_table('lpo_attachments')
    op.drop_index(op.f('ix_lpos_id'), table_name='lpos')
    op.drop_table('lpos')
    # ### end Alembic commands ###
