"""Add material receipt tables

Revision ID: b06ec452c1e3
Revises: 6aab78507ee6
Create Date: 2025-09-19 10:45:19.331472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b06ec452c1e3'
down_revision: Union[str, Sequence[str], None] = '6aab78507ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('received_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requisition_id'], ['material_requisitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_receipts_id'), 'material_receipts', ['id'], unique=False)
    op.create_table('material_receipt_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blob_url', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['material_receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_receipt_images_id'), 'material_receipt_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_receipt_images_id'), table_name='material_receipt_images')
    op.drop_table('material_receipt_images')
    op.drop_index(op.f('ix_material_receipts_id'), table_name='material_receipts')
    op.drop_table('material_receipts')
    # ### end Alembic commands ###
