"""Add acknowledgement to material receipt

Revision ID: b148321ad195
Revises: 6898f0262850
Create Date: 2025-09-30 10:44:57.918673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b148321ad195'
down_revision: Union[str, Sequence[str], None] = '6898f0262850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_receipts', sa.Column('acknowledged_by_receiver', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_receipts', 'acknowledged_by_receiver')
    # ### end Alembic commands ###
