"""Add special notes to material requisition

Revision ID: bce36e94c676
Revises: 40cc876b2675
Create Date: 2025-09-30 12:33:19.402605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce36e94c676'
down_revision: Union[str, Sequence[str], None] = '40cc876b2675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_requisitions', sa.Column('special_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_requisitions', 'special_notes')
    # ### end Alembic commands ###
