"""Add job card assignment log table

Revision ID: c9eee74fb1bb
Revises: 12a59a80ef07
Create Date: 2025-09-22 09:46:58.848445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9eee74fb1bb'
down_revision: Union[str, Sequence[str], None] = '12a59a80ef07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jc_assignment_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('job_card_id', sa.Integer(), nullable=False),
    sa.Column('assigned_supervisor_id', sa.Integer(), nullable=False),
    sa.Column('assigned_foreman_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_foreman_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_supervisor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_card_id'], ['job_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jc_assignment_logs_id'), 'jc_assignment_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jc_assignment_logs_id'), table_name='jc_assignment_logs')
    op.drop_table('jc_assignment_logs')
    # ### end Alembic commands ###
