"""Add qs validation table

Revision ID: d29512833bab
Revises: 0efa80422b5f
Create Date: 2025-10-08 15:42:52.491913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd29512833bab'
down_revision: Union[str, Sequence[str], None] = '0efa80422b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qs_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost_estimation_sheet_link', sa.Text(), nullable=False),
    sa.Column('validated_boq_link', sa.Text(), nullable=False),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('validated_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['design_stages_v3.id'], ),
    sa.ForeignKeyConstraint(['validated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qs_validations')
    # ### end Alembic commands ###
