"""Add procurement workflow and update Supplier model

Revision ID: d9ebc8f0f3e3
Revises: 03b45eab6e2f
Create Date: 2025-09-06 16:01:39.457583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9ebc8f0f3e3'
down_revision: Union[str, Sequence[str], None] = '03b45eab6e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('material_requisitions', sa.Column('mr_number', sa.String(), nullable=True))

    # CORRECTED LINE
    op.add_column('material_requisitions', sa.Column('status', sa.String(), nullable=False, server_default='Pending'))

    op.add_column('material_requisitions', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.add_column('material_requisitions', sa.Column('lpo_number', sa.String(), nullable=True))

    # CORRECTED LINE
    op.add_column('material_requisitions', sa.Column('pm_approval', sa.String(), nullable=True, server_default='Pending'))

    # CORRECTED LINE
    op.add_column('material_requisitions', sa.Column('qs_approval', sa.String(), nullable=True, server_default='Pending'))

    op.add_column('material_requisitions', sa.Column('payment_status', sa.String(), nullable=True))
    op.add_column('material_requisitions', sa.Column('remarks', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'material_requisitions', ['mr_number'])
    op.create_foreign_key(None, 'material_requisitions', 'suppliers', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'material_requisitions', type_='foreignkey')
    op.drop_constraint(None, 'material_requisitions', type_='unique')
    op.drop_column('material_requisitions', 'remarks')
    op.drop_column('material_requisitions', 'payment_status')
    op.drop_column('material_requisitions', 'qs_approval')
    op.drop_column('material_requisitions', 'pm_approval')
    op.drop_column('material_requisitions', 'lpo_number')
    op.drop_column('material_requisitions', 'supplier_id')
    op.drop_column('material_requisitions', 'status')
    op.drop_column('material_requisitions', 'mr_number')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
