"""Add job card comments table

Revision ID: e4a840333f8a
Revises: b06ec452c1e3
Create Date: 2025-09-20 09:32:21.333681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4a840333f8a'
down_revision: Union[str, Sequence[str], None] = 'b06ec452c1e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jc_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('job_card_id', sa.Integer(), nullable=False),
    sa.Column('comment_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_card_id'], ['job_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jc_comments_id'), 'jc_comments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jc_comments_id'), table_name='jc_comments')
    op.drop_table('jc_comments')
    # ### end Alembic commands ###
