"""Add QS to userrole enum

Revision ID: e571fde6a997
Revises: 81ddc3ef4786
Create Date: 2025-09-11 15:14:07.121385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e571fde6a997'
down_revision: Union[str, Sequence[str], None] = '81ddc3ef4786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userrole ADD VALUE 'QS'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
