"""Move video feature from Form A to Form C

Revision ID: f66be99a0a37
Revises: 004e2bd09eac
Create Date: 2025-09-08 10:09:00.766576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f66be99a0a37'
down_revision: Union[str, Sequence[str], None] = '004e2bd09eac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toolbox_videos', sa.Column('site_officer_report_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('toolbox_videos_job_card_id_fkey'), 'toolbox_videos', type_='foreignkey')
    op.create_foreign_key(None, 'toolbox_videos', 'site_officer_reports', ['site_officer_report_id'], ['id'])
    op.drop_column('toolbox_videos', 'job_card_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toolbox_videos', sa.Column('job_card_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'toolbox_videos', type_='foreignkey')
    op.create_foreign_key(op.f('toolbox_videos_job_card_id_fkey'), 'toolbox_videos', 'job_cards', ['job_card_id'], ['id'])
    op.drop_column('toolbox_videos', 'site_officer_report_id')
    # ### end Alembic commands ###
