- name: Deploy to Azure Container Apps
  uses: Azure/container-apps-deploy-action@v2
  with:
    resourceGroup: ${{ env.RESOURCE_GROUP }}
    location: ${{ env.LOCATION }}
    acrName: ${{ env.ACR_NAME }}
    containerAppEnvironment: ${{ env.CONTAINER_APP_ENV }}
    containerAppName: ${{ env.CONTAINER_APP_NAME }}
    imageToDeploy: ${{ env.ACR_NAME }}.azurecr.io/metamorphic-job-card:${{ github.sha }}
    targetPort: 8000
    ingress: external

    # Push values into ACA secrets
    secrets: |
      DATABASE_URL=${{ secrets.DATABASE_URL }}
      SECRET_KEY=${{ secrets.SECRET_KEY }}
      AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

    # Expose them to the container via secret references
    environmentVariables: |
      DATABASE_URL=secretref:DATABASE_URL
      SECRET_KEY=secretref:SECRET_KEY
      AZURE_STORAGE_CONNECTION_STRING=secretref:AZURE_STORAGE_CONNECTION_STRING
      OPENAI_API_KEY=secretref:OPENAI_API_KEY
